services:
    bqueuebundle.job_manager:
        class: Strnoar\BQueueBundle\Jobs\JobManager
        arguments:
            ["@logger", "%strnoar_b_queue%"]
        calls:
            - [setContainer, ["@service_container"]]

    bqueuebundle.queue_listen_command:
        class: Strnoar\BQueueBundle\Command\QueueListenCommand
        calls:
            - [setContainer, ["@service_container"]]
            - [setParameters, ["%strnoar_b_queue%"]]
